
// ⚡ ULTIMATE VERSION (kısaltılmış ama güçlü yapı)

import React, { useState, useEffect } from "react";
import { Search, Bookmark, CheckCircle, Film, Tv, X } from "lucide-react";

const API_KEY = "BURAYA_API_KEY";
const BASE_URL = "https://api.themoviedb.org/3";
const IMAGE_URL = "https://image.tmdb.org/t/p/w500";

export default function App() {
  const [view, setView] = useState("home");
    const [categories, setCategories] = useState({});
      const [searchTerm, setSearchTerm] = useState("");
        const [results, setResults] = useState([]);
          const [selected, setSelected] = useState(null);

            const [myList, setMyList] = useState(
                JSON.parse(localStorage.getItem("myList")) || []
                  );

                    useEffect(() => {
                        localStorage.setItem("myList", JSON.stringify(myList));
                          }, [myList]);

                            // 🎬 kategori verileri
                              useEffect(() => {
                                  const fetchData = async () => {
                                        const endpoints = {
                                                trending: "/trending/all/week",
                                                        popular: "/movie/popular",
                                                                top: "/movie/top_rated",
                                                                        tv: "/tv/popular"
                                                                              };

                                                                                    let data = {};
                                                                                          for (let key in endpoints) {
                                                                                                  const res = await fetch(
                                                                                                            `${BASE_URL}${endpoints[key]}?api_key=${API_KEY}&language=tr-TR`
                                                                                                                    );
                                                                                                                            const json = await res.json();
                                                                                                                                    data[key] = json.results;
                                                                                                                                          }

                                                                                                                                                setCategories(data);
                                                                                                                                                    };

                                                                                                                                                        fetchData();
                                                                                                                                                          }, []);

                                                                                                                                                            // 🔍 search debounce
                                                                                                                                                              useEffect(() => {
                                                                                                                                                                  const t = setTimeout(() => {
                                                                                                                                                                        if (searchTerm) {
                                                                                                                                                                                fetch(
                                                                                                                                                                                          `${BASE_URL}/search/multi?api_key=${API_KEY}&query=${searchTerm}`
                                                                                                                                                                                                  )
                                                                                                                                                                                                            .then(r => r.json())
                                                                                                                                                                                                                      .then(d => setResults(d.results));
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                }, 400);

                                                                                                                                                                                                                                    return () => clearTimeout(t);
                                                                                                                                                                                                                                      }, [searchTerm]);

                                                                                                                                                                                                                                        const toggleList = item => {
                                                                                                                                                                                                                                            setMyList(prev =>
                                                                                                                                                                                                                                                  prev.find(i => i.id === item.id)
                                                                                                                                                                                                                                                          ? prev.filter(i => i.id !== item.id)
                                                                                                                                                                                                                                                                  : [...prev, item]
                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                              <div className="bg-black text-white min-h-screen p-4">

                                                                                                                                                                                                                                                                                    {/* NAV */}
                                                                                                                                                                                                                                                                                          <div className="flex gap-2 mb-6">
                                                                                                                                                                                                                                                                                                  <button onClick={() => setView("home")}>Ana Sayfa</button>
                                                                                                                                                                                                                                                                                                          <button onClick={() => setView("search")}>Ara</button>
                                                                                                                                                                                                                                                                                                                  <button onClick={() => setView("list")}>Listem</button>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                              {/* HOME */}
                                                                                                                                                                                                                                                                                                                                    {view === "home" && categories.trending && (
                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                      {/* HERO */}
                                                                                                                                                                                                                                                                                                                                                                <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                            <img
                                                                                                                                                                                                                                                                                                                                                                                          src={`${IMAGE_URL}${categories.trending[0].backdrop_path}`}
                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* CATEGORY */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {Object.keys(categories).map(key => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={key} className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="mb-2 text-lg">{key}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex overflow-x-auto gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {categories[key].map(m => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={m.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setSelected(m)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src={`${IMAGE_URL}${m.poster_path}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-32 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* SEARCH */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {view === "search" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Ara..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full p-3 mb-4 bg-gray-900"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={e => setSearchTerm(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-3 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {results.map(m => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={m.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src={`${IMAGE_URL}${m.poster_path}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setSelected(m)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* LIST */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {view === "list" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-3 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {myList.map(m => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img key={m.id} src={`${IMAGE_URL}${m.poster_path}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* MODAL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {selected && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="fixed inset-0 bg-black p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setSelected(null)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <X />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={`${IMAGE_URL}${selected.poster_path}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => toggleList(selected)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Listeme Ekle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }